[package]
name = "vercel_lambda"
version = "0.2.0"
authors = ["Antonio Nuno Monteiro <anmonteiro@gmail.com>"]
edition = "2018"
description = "Rust bindings for Vercel Lambdas"
keywords = ["AWS", "Lambda", "Vercel", "Rust"]
license = "MIT"
homepage = "https://github.com/mike-engel/vercel-rust"
repository = "https://github.com/mike-engel/vercel-rust"
documentation = "https://docs.rs/vercel_lambda"
include = [
    "src/*.rs",
    "Cargo.toml"
]

[dependencies]
serde = "^1"
serde_json = "^1"
serde_derive = "^1"
http = "0.1"
tokio = "^0.1"
base64 = "0.10"
log = "^0.4"
lambda_runtime = "0.2.0"
